version: "3.8"
services:
  mongodb:
    image: mongo:5.0
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:
