version: '3'

services:
  app:
    image: document-base-server
    environment:
      DATABASE_URL:
      OPENAI_API_KEY:
      GOOGLE_SEARCH_API_KEY:
      GOOGLE_SEARCH_ENGINE_ID:
      ZYTE_API_KEY:
      ZYTE_API_ENDPOINT:
    ports:
      - "3000:3000"
