name: Server - Build Check

on:
  pull_request:
    paths:
      - "packages/server/**"

env:
  IMAGE_TAG: document-base

jobs:
  check:
    name: Server - Build check
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Server - Build docker image
        run: docker build -t $IMAGE_TAG --target=build ./packages/server
