name: Web ChatBot - Build Check

on:
  pull_request:
    paths:
      - 'packages/web-chatbot/**'

env:
  IMAGE_TAG: document-base-web-chatbot

jobs:
  check:
    name: Run build check
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3

      - run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"

      - name: Install Dependencies
        run: npm install

      - name: Run Linter
        run: npx nx run web-chatbot:lint

      - name: Run Test
        run: npx nx run web-chatbot:test

      - name: Build Docker Image
        run: npx nx run web-chatbot:docker-build -- -t $IMAGE_TAG
