name: Build Check

on:
  pull_request:
    # types: [opened, reopened]
    paths:
      - "packages/server/**"

env:
  IMAGE_TAG: document-base

jobs:
  test:
    name: Run Build Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Build the Docker Image
        run: docker build -t $IMAGE_TAG --target=build ./packages/server

      - name: Run Prettier
        run: docker run $IMAGE_TAG sh -c 'npm run format'

      - name: Run ESLint
        run: docker run $IMAGE_TAG sh -c 'npm run lint'

      # - name: Run tests
      #   run: docker run $IMAGE_TAG sh -c 'npm run test'
