name: Build Check

on:
  pull_request:

env:
  IMAGE_TAG: document-base

jobs:
  check:
    name: Run Build Check
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3

      - run: |
          echo "BASE: ${{ env.NX_BASE }}"
          echo "HEAD: ${{ env.NX_HEAD }}"

      - name: Install Dependencies
        run: npm install

      - name: Run Linter
        run: npx nx run server:lint

      - name: Run Test
        run: npx nx run server:test

      - name: Build Docker Image
        run: npx nx run server:docker-build -- -t $IMAGE_TAG
